### ISSUE TITLE
Unsupervised Learning, Week 2 Practice Lab 2: Programming Assignment: Deep Learning for Content-Based Filtering

### ISSUE THREAD

**Issue by TestAccountLearn** [shantanu1109/Coursera-DeepLearning.AI-Stanford-University-Machine-Learning-Specialization#2]
Hi, 
Thank you very much for providing content for the Coursera course, you have been helping me a lot.
However, there is an issue I have been stuck at. It seems that the outline for the Content-Based Filtering practice lab has been changed and I am stuck in passing that lab. 
I would be really grateful if you could help me further with that since it seems your input is outdated on that part.

**Comment by shantanu1109** [comment]
Hi,
I'm glad to be helpful. I understand your concern about the change in
outline for the Content-Based Filtering practice lab. It's a concern for
many learners that some minute changes are made in practical lab
assignments over time. And learner's get stuck trying to solve the new
updated part. Again, thanks for raising the concern. Would you mind sending
me the updated version of the same practical. I would surely like to try
solving it.

**Comment by CoBotKazeem** [comment]
Hello,
Big thanks for the content you provide. I am also having the same issue. 

I have attached the updated version of the same practice.
[C3_W2_RecSysNN_Assignment.md](https://github.com/shantanu1109/Coursera-DeepLearning.AI-Stanford-University-Machine-Learning-Specialization/files/11782284/C3_W2_RecSysNN_Assignment.md)

**Comment by shantanu1109** [comment]
Ok, I will get back to you soon.

**Comment by Kyrillos-Ghattas** [comment]
Hello,
Thank you so much for providing such content. Again, it seems that the programming assignment of Deep Learning for Content-Based Filtering has been changed and I want your help with that lab.
It would be much more appreciated if you could help me further with that.

**Comment by shantanu1109** [comment]
Hello,
Kyrillos-Ghattas.




Can you send me the file so I can go through the required changes?

**Comment by Kyrillos-Ghattas** [comment]
[Files.zip](https://github.com/shantanu1109/Coursera-DeepLearning.AI-Stanford-University-Machine-Learning-Specialization/files/12869577/Files.zip)

**Comment by shantanu1109** [comment]
Got them, thanks!

**Comment by shantanu1109** [comment]
Here's ur updated version.

**Comment by Kyrillos-Ghattas** [comment]
Where is the .ipynb file?

**Comment by shantanu1109** [comment]
I have attached it to the mail.

**Comment by Kyrillos-Ghattas** [comment]
Sorry, can you send the .ipynb file only? to find which part I stuck with.
